sudo: required
language: python

cache: pip

python:
  - "3.6"

services:
  - docker

install:
  - docker build -t yafas/yafas-server .
  - docker run -dit --name yafas-server-ci yafas/yafas-server
  - docker exec yafas-server-ci pip install coveralls

script:
  - docker exec yafas-server-ci flake8
  - docker exec yafas-server-ci coverage run --source yafas -m pytest

after_success:
  - docker cp yafas-server-ci:/app/.coverage ./
  - sed -i 's@/app@'"$TRAVIS_BUILD_DIR"'@g' .coverage
  - pip install coveralls
  - coveralls

deploy:
  skip_cleanup: true
  provider: script
  script: ./docker-push.sh
  on:
    branch: master

after_script:
  - docker rm -f yafas-server-ci
